ch2_2_3: build/ch2_2_3.o build/ch2_1_3.o
	gcc -o ch2_2_3 build/ch2_2_3.o build/ch2_1_3.o
ch2_2_3.o: ch2_2_3.c ch2_1_3.h
	gcc -c build/ch2_2_3.o ch2_2_3.c
ch2_1_3.o: ch2_1_3.c ch2_1_3.h
	gcc -c build/ch2_1_3.o ch2_1_3.c
